Parsmount2/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsmount2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test1Entities : DbContext
    {
        public test1Entities()
            : base("name=test1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t1> t1 { get; set; }
        public virtual DbSet<t3> t3 { get; set; }
    }
}

Parsmount2/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'D:\xxx\VS 2022\Parsmount2\Parsmount2\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Parsmount2/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Parsmount2/Models/t1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsmount2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t1
    {
        public int c1 { get; set; }
        public Nullable<int> c2 { get; set; }
        public string c3 { get; set; }
    }
}

Parsmount2/Models/t3.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsmount2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t3
    {
        public int cc1 { get; set; }
        public Nullable<int> cc2 { get; set; }
        public string cc3 { get; set; }
    }
}

Parsmount2/Controllers/DefaultController.cs
using Parsmount2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Parsmount2.Controllers
{
    public class DefaultController : Controller
    {
        test1Entities db = new test1Entities();
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DisplayProduct()
        {
            List<t1> list = db.t1.OrderByDescending(x => x.c1).ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult CreateProduct()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateProduct(t1 pro)
        {
            db.t1.Add(pro);
            db.SaveChanges();
            return RedirectToAction("DisplayProduct");
        }




        [HttpGet]
        public ActionResult DisplayProduct2()
        {
            List<t3> list = db.t3.OrderByDescending(x => x.cc1).ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult CreateProduct2()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateProduct2(t3 pro)
        {
            db.t3.Add(pro);
            db.SaveChanges();
            return RedirectToAction("DisplayProduct2");
        }

        [HttpGet]
        public ActionResult UpdateProduct(int id)
        {
            t1 pr = db.t1.Where(x => x.c1 == id).SingleOrDefault();
            return View(pr);
        }

        [HttpPost]
        public ActionResult UpdateProduct(int id, t1 pro)
        {
            t1 pr = db.t1.Where(x => x.c1 == id).SingleOrDefault();
            pr.c2 = pro.c2;
            pr.c3 = pro.c3;
            db.SaveChanges();
            return RedirectToAction("DisplayProduct");
        }
    }    
}

Parsmount2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Parsmount2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Parsmount2/Views/Default/CreateProduct.cshtml
@model Parsmount2.Models.t1

@{
    ViewBag.Title = "CreateProduct";
}

<h2>CreateProduct</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>t1</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.c2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.c2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.c2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.c3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.c3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.c3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Parsmount2/Views/Default/CreateProduct2.cshtml
@model Parsmount2.Models.t3

@{
    ViewBag.Title = "CreateProduct2";
}

<h2>CreateProduct2</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>t3</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.cc2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cc2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cc2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cc3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cc3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cc3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "DisplayProduct2")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Parsmount2/Views/Default/DisplayProduct.cshtml
@model IEnumerable<Parsmount2.Models.t1>

@{
    ViewBag.Title = "DisplayProduct";
}

<h2>DisplayProduct</h2>

<p>
    @Html.ActionLink("Create New", "CreateProduct")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.c2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.c3)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.c2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.c3)
        </td>
        <td>
            @Html.ActionLink("Edit", "UpdateProduct", new { id=item.c1 }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Details", "Details", new { id=item.c1 }, new { @class = "btn btn-success" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.c1 }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

Parsmount2/Views/Default/DisplayProduct2.cshtml
@model IEnumerable<Parsmount2.Models.t3>

@{
    ViewBag.Title = "DisplayProduct2";
}

<h2>DisplayProduct2</h2>

<p>
    @Html.ActionLink("Create New", "CreateProduct2")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.cc2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cc3)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.cc2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cc3)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.cc1 }) |
            @Html.ActionLink("Details", "Details", new { id=item.cc1 }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.cc1 })
        </td>
    </tr>
}

</table>

Parsmount2/Views/Default/UpdateProduct.cshtml
@model Parsmount2.Models.t1

@{
    ViewBag.Title = "UpdateProduct";
}

<h2>UpdateProduct</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>t1</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.c1)

        <div class="form-group">
            @Html.LabelFor(model => model.c2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.c2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.c2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.c3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.c3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.c3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "DisplayProduct","t1", new{ @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

<div>
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Parsmount2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Parsmount2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Parsmount2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Parsmount2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Parsmount", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("DisplayProduct", "DisplayProduct", "Default")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>